version: '3'

services:
  backend:
    build: ./
    container_name: shop_container
    working_dir: /shop
    ports:
      - 8010:8000
    volumes:
      - ./src:/shop/src
      - ./commands:/shop/commands
    command:
      - ./commands/start_server_dev.sh
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }


